server:
  port: 8082

spring:
  datasource:
    url:
    username:
    password:
    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/