server:
  port: 8084
  shutdown: graceful
  tomcat:
    threads:
      max: 500
      min-spare: 20
    max-connections: 500
    accept-count: 200
    max-http-form-post-size: 10MB

logging:
  level:
    ROOT: INFO
    com.apus.base: INFO
#    org.hibernate.sql: DEBUG
#    org.hibernate.type: TRACE
#    org.springframework.orm.jpa: DEBUG
#    org.springframework.transaction: DEBUG
#    org.hibernate.engine.transaction.internal.TransactionImpl: DEBUG

spring:
  application:
    name: product-service
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.jdbc.lob.non_contextual_creation: true
      # modify batch size as necessary
      hibernate.jdbc.batch_size: 50
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
      hibernate.format_sql: true
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/shoe_map?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&reWriteBatchedInserts=true
    username: postgres
    password: 123
  #    hikari:
  #      minimumIdle: 5
  #      maximumPoolSize: 20
  #      idleTimeout: 30000
  #      maxLifetime: 2000000
  #      connectionTimeout: 30000
  # Log tracing
  zipkin:
    enabled: false
    baseUrl: http://zipkin.dev.afstech.vn:9411
  sleuth:
    enabled: true

eureka:
  client:
    enabled: false
    healthcheck:
      enabled: true
    fetch-registry: true
    register-with-eureka: true
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
    service-url:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    appname: example-service
    instanceId: example-service:${spring.application.instance-id:${random.value}}
    prefer-ip-address: true
    virtual-host-name: example-service
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    status-page-url-path: ${management.endpoints.web.base-path}/info
    health-check-url-path: ${management.endpoints.web.base-path}/health
    metadata-map:
      zone: primary

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: [ 'health', 'info' ]

feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  system-alias: alias-code
  upload_folder_alias: root
  file_url:
  token: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJzeXN0ZW1fYWRtaW4iLCJzY29wZSI6WyJhbGwiXSwiaWQiOjM4NywiZXhwIjoxNjgyNDQyMjY1LCJpYXQiOjE2ODI0MzkyNjUsImF1dGhvcml0aWVzIjpbInVhYXBlci0xNiIsIlNZU1RFTV9BRE1JTi0zMSJdLCJqdGkiOiJ5VFNhMDJWcWdxNWxUV1AtMGgyRExRbVZBMm8iLCJjbGllbnRfaWQiOiJ0ZXN0In0.YI9DkwTc08doBqhFjHQbJfuCXpYJHM0JCd9BSJqozQtUHfDtpD44AmrWSGOL9iIyBIh9hAwWqXOx5AqXk5WXgflrJ24cjxiRE_ArhbWt1qXOlqzvDi-qWuUhAowNd5emTNpF6jT0A-r4DvbdFA8p9AldNSDfWC2OHIUNPlpzail-AdFm2cn8XxShqbQBaKvV03djiUYqrYbcp0bQSajwhUMPdfP9j5zgA6O6W975bv3pEBcapkwqPzsVvv2XSkjOHArdSRIvnYTpp8VflPY6xpOdTm5N2hp1ip9SjOJRLX2fz0HVmGleY9s_rqeUjHoEWgFnRWrtkYZ-Zj8lS2xGiQ
