spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/product_manufactor_service?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&reWriteBatchedInserts=true
    username: postgres
    password: 123456
